# Generated by Django 5.1.1 on 2024-10-28 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('score', models.IntegerField()),
                ('position', models.IntegerField(default=0)),
                ('figure', models.CharField(max_length=150)),
                ('is_arrested', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('заполнен', 'Заполнен'), ('есть места', 'Есть места')], default='есть места', max_length=20)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('init_score', models.IntegerField(default=3000)),
                ('is_private', models.BooleanField(default=False)),
                ('player_count', models.IntegerField(default=1)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_rooms', to='main.player')),
                ('players', models.ManyToManyField(blank=True, related_name='players_rooms', to='main.player')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ожидает ответа', 'Ожидает ответа'), ('принят', 'Принят'), ('отклонён', 'Отклонён')], default='ожидает ответа', max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gametime', models.FloatField(blank=True, null=True)),
                ('realty', models.ManyToManyField(blank=True, to='main.realty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
        ),
    ]
