image: python:3.9-slim

services:
  - name: postgres:alpine
    alias: postgres
    variables:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Monopoly_game

stages:
  - build
  - test
  - deploy

variables:
  DATABASE_URL: postgres://postgres_user:123@postgres:5432/Monopoly_game
  REDIS_URL: redis://redis:6379

before_script:
  - pip install --upgrade pip
  - pip install -r backend/django/requirements.txt

build:
  stage: build
  script:
    - echo "Building the application..."
    - docker build -t myapp:latest ./backend/django

test:
  stage: test
  script:
    - echo "Running migrations..."
    - python backend/django/manage.py migrate
    - echo "Running tests..."
    - python backend/django/manage.py test

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying the application..."
    - docker pull myapp:latest
    - ssh user@your-server "docker run -d --rm --name backend-container -e DATABASE_URL=$DATABASE_URL myapp:latest"
