version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '${NGINX_HTTP_PORT:-80}:80'  # По умолчанию порт 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - backend
    networks:
      - dev

  backend:
    container_name: backend
    build:
      context: ./backend/django
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_HOST: postgres
    working_dir: /usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - backend/django/docker/env/.env.dev
    volumes:
      - ./backend:/usr/src/app  # Подключение локальных файлов
    depends_on:
      - postgres
      - redis
    networks:
      - dev

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  redis:
    image: redis:latest
    networks:
      - dev

volumes:
  postgres_data:

networks:
  dev: