services:
  backend:
    container_name: backend-test
    build:
      context: ./backend/django
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Monopoly_game
      DATABASE_URL: postgres://postgres_user:123@postgres:5432/Monopoly_game
    working_dir: /usr/src/app/
    volumes:
      - ./backend/django:/usr/src/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    container_name: postgres-test
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Monopoly_game
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      
  redis:
    image: redis:alpine
    container_name: redis-test
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-test
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_pass
    ports:
      - "15672:15672"  
      - "5672:5672"    
    restart: always

  celery:
    build:
      context: ./backend/django
      dockerfile: Dockerfile
    container_name: celery-test
    restart: always
    working_dir: /usr/src/app/
    environment:
      REDIS_LOCATION: redis://redis-test:6379/0
      CELERY_BROKER_URL: amqp://rabbit_user:rabbit_pass@rabbitmq-test:5672//
      CELERY_RESULT_BACKEND: redis://redis-test:6379/0
    volumes:
      - ./backend/django:/usr/src/app
    command: celery -A celery worker --loglevel=info
    depends_on:
      - rabbitmq
      - redis

volumes:
  pgdata:
