# Generated by Django 5.1.1 on 2024-12-21 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('заполнен', 'Заполнен'), ('есть места', 'Есть места')], default='есть места', max_length=20)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('init_score', models.PositiveIntegerField(default=3000)),
                ('is_private', models.BooleanField(default=True)),
                ('player_count', models.PositiveIntegerField(default=4)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
